### ISSUE TITLE
bluepill examples outdated?

### ISSUE THREAD

**Issue by x37v** [mendelt/embedded-midi#2]
looks like the API has changed since those examples were written?

**Comment by mendelt** [comment]
Thank you, looks like the stm32f1xx-hal is quite outdated and there is a new version of embedded-hal. I'll see if I can update things.
Did you find any specific issues?

**Comment by x37v** [comment]
> Did you find any specific issues?

https://github.com/mendelt/embedded-midi/blob/4162213a7593fcbc69cc84da574366583ba2f646/bluepill-examples/examples/send_notes.rs#L6

`MidiEvent` isn't in the library anymore..

**Comment by mendelt** [comment]
Ah, stupid of me. I moved all that to the midi-types crate but forgot to fix the example. Thank you for noticing.

**Comment by mendelt** [comment]
The examples now compile. I'll have to rebuild my test-setup this weekend to test if they actually still work but I would be surprised if they don't.
Looks like I also have to update some dependencies.
Thanks again for reporting this issue!

**Comment by x37v** [comment]
you're welcome!
